version: '3.8'

services:
  clipfactory:
    build: .
    ports:
      - "8000:8000"
    environment:
      # Flask Configuration
      - FLASK_ENV=production
      - FLASK_DEBUG=false
      
      # GPU Configuration
      - CUDA_VISIBLE_DEVICES=0
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      
      # Application Configuration
      - CLIPPER_MAX_WORKERS=4
      - FFMPEG_PATH=ffmpeg
      
      # R2 Storage Configuration (set these in Vast.ai environment)
      - R2_ENDPOINT_URL=${R2_ENDPOINT_URL}
      - R2_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID}
      - R2_SECRET_ACCESS_KEY=${R2_SECRET_ACCESS_KEY}
      - R2_BUCKET_NAME=${R2_BUCKET_NAME}
      
      # OpenAI/Groq API Keys (set these in Vast.ai environment)
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      
    volumes:
      - ./temp:/app/temp
      - ./uploads:/app/uploads
      - ./downloads:/app/downloads
    
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/status/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s